In [2]:
import pandas as pd

In [5]:
filepath = "/Users/weiweixu/Downloads/2016 Fall/Programming for Data Science/NYPD_Motor_Vehicle_Collisions.csv"

# change to your own path

In [7]:
df = pd.read_csv(filepath)

In [11]:
df

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,09/18/2016,19:09,QUEENS,11422.0,NaN,NaN,NaN,NaN,NaN,234-32 131 AVENUE,...,NaN,NaN,NaN,NaN,3522011,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
1,09/18/2016,19:09,BROOKLYN,11237.0,NaN,NaN,NaN,NaN,NaN,140 MORGAN AVENUE,...,Driver Inattention/Distraction,NaN,NaN,NaN,3522438,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
2,09/18/2016,1:09,MANHATTAN,10012.0,NaN,NaN,NaN,DELANCEY STREET,BOWERY,NaN,...,Unspecified,NaN,NaN,NaN,3523763,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
3,09/18/2016,1:09,NaN,NaN,40.862498,-73.934185,"(40.8624983, -73.9341848)",NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3524356,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
4,09/18/2016,20:09,BROOKLYN,11229.0,NaN,NaN,NaN,AVENUE W,PLUMB 1 STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,3522651,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
5,09/18/2016,20:09,MANHATTAN,10003.0,NaN,NaN,NaN,NaN,NaN,355 BOWERY,...,Unspecified,NaN,NaN,NaN,3522315,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
6,08/25/2015,19:00,NaN,NaN,40.732941,-73.920382,"(40.7329414, -73.9203819)",NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3284922,PASSENGER VEHICLE,TAXI,NaN,NaN,NaN
7,07/27/2012,22:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2833714,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
8,05/17/2014,0:45,NaN,NaN,NaN,NaN,NaN,PENNSYLVANIA AVENUE,RIVERDALE AVENUE,NaN,...,NaN,NaN,NaN,NaN,336679,NaN,NaN,NaN,NaN,NaN
9,08/12/2016,1:08,QUEENS,11377.0,NaN,NaN,NaN,QUEENS BOULEVARD,69 STREET,NaN,...,Unspecified,NaN,NaN,NaN,3498919,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
10,08/12/2016,20:08,BRONX,10460.0,NaN,NaN,NaN,NaN,NaN,948 EAST 179 STREET,...,Unspecified,NaN,NaN,NaN,3499511,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
11,08/12/2016,20:08,BRONX,10466.0,NaN,NaN,NaN,EDENWALD AVENUE,BRUNER AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3500136,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
12,08/12/2016,20:08,BROOKLYN,11216.0,NaN,NaN,NaN,NaN,NaN,1323 FULTON STREET,...,Unspecified,NaN,NaN,NaN,3499591,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
13,08/12/2016,20:08,BROOKLYN,11226.0,NaN,NaN,NaN,NaN,NaN,500 OCEAN AVENUE,...,Unspecified,NaN,NaN,NaN,3501084,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
14,08/12/2016,20:08,BROOKLYN,11235.0,NaN,NaN,NaN,NaN,NaN,2805 AVENUE Y,...,Unspecified,NaN,NaN,NaN,3500227,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
15,09/18/2016,21:09,QUEENS,11420.0,NaN,NaN,NaN,NaN,NaN,114-18 120 STREET,...,Unspecified,NaN,NaN,NaN,3522320,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
16,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,ROGERS AVENUE,NaN,NaN,...,Other Vehicular,Unspecified,NaN,NaN,3523254,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN
17,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,UTOPIA PARKWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3523140,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
18,09/18/2016,22:09,BROOKLYN,11211.0,NaN,NaN,NaN,METROPOLITAN AVENUE,GARDNER AVENUE,NaN,...,NaN,NaN,NaN,NaN,3523286,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
19,08/12/2016,20:08,MANHATTAN,10036.0,NaN,NaN,NaN,10 AVENUE,WEST 41 STREET,NaN,...,Unspecified,NaN,NaN,NaN,3500791,SMALL COM VEH(4 TIRES),PASSENGER VEHICLE,NaN,NaN,NaN
20,08/12/2016,20:08,QUEENS,11101.0,NaN,NaN,NaN,44 DRIVE,10 STREET,NaN,...,Unspecified,NaN,NaN,NaN,3499705,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
21,08/12/2016,20:08,QUEENS,11377.0,NaN,NaN,NaN,NaN,NaN,69-10 34 AVENUE,...,Unspecified,NaN,NaN,NaN,3499764,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
22,08/12/2016,20:08,NaN,NaN,NaN,NaN,NaN,KINGS HIGHWAY,CLARENDON ROAD,NaN,...,Unspecified,NaN,NaN,NaN,3501024,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
23,05/03/2016,8:00,QUEENS,11385.0,40.707891,-73.909622,"(40.7078905, -73.9096224)",NaN,NaN,1934 GREENE AVENUE,...,Unspecified,NaN,NaN,NaN,3434031,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
24,05/03/2016,8:00,NaN,NaN,NaN,NaN,NaN,CROSSBAY BOULEVARD,SHORE PARKWAY,NaN,...,Unspecified,NaN,NaN,NaN,3434064,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
25,05/03/2016,8:09,BROOKLYN,11208.0,40.678828,-73.866171,"(40.6788277, -73.866171)",NaN,NaN,1168 LIBERTY AVENUE,...,NaN,NaN,NaN,NaN,3433897,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
26,05/03/2016,8:10,MANHATTAN,10031.0,40.830669,-73.944886,"(40.8306685, -73.9448864)",NaN,NaN,528 WEST 153 STREET,...,Unspecified,NaN,NaN,NaN,3434479,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
27,09/17/2016,13:09,STATEN ISLAND,10301.0,NaN,NaN,NaN,RICHMOND TERRACE,HAMILTON AVENUE,NaN,...,NaN,NaN,NaN,NaN,3524007,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
28,09/17/2016,13:09,NaN,NaN,NaN,NaN,NaN,MORNINGSTAR ROAD,WALKER STREET,NaN,...,NaN,NaN,NaN,NaN,3521752,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
29,09/17/2016,13:09,NaN,NaN,40.789540,-73.982252,"(40.7895396, -73.9822521)",NaN,NaN,NaN,...,Other Vehicular,Other Vehicular,Following Too Closely,NaN,3521917,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913773,07/11/2012,9:00,NaN,NaN,40.746107,-73.766791,"(40.746107, -73.7667908)",NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3078747,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913774,07/11/2012,9:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2912127,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913775,07/10/2012,12:00,NaN,NaN,NaN,NaN,NaN,ASTORIA BOULEVARD,31 STREET,NaN,...,Unspecified,NaN,NaN,NaN,272667,PASSENGER VEHICLE,PICK-UP TRUCK,NaN,NaN,NaN
913776,07/10/2012,18:00,NaN,NaN,NaN,NaN,NaN,KERMIT AVENUE,PARKINSON AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,293261,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913777,07/10/2012,20:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2918666,PASSENGER VEHICLE,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN
913778,07/09/2012,13:45,NaN,NaN,NaN,NaN,NaN,PARK AVENUE,HALL STREET,NaN,...,NaN,NaN,NaN,NaN,191585,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913779,07/09/2012,4:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2879038,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913780,07/08/2012,22:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3016748,MOTORCYCLE,NaN,NaN,NaN,NaN
913781,07/08/2012,2:35,NaN,NaN,40.835486,-73.949394,"(40.8354859, -73.9493936)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2872826,OTHER,NaN,NaN,NaN,NaN
913782,07/07/2012,13:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3121385,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913783,07/07/2012,14:40,NaN,NaN,NaN,NaN,NaN,EAST 135 STREET,3 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,72655,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913784,07/07/2012,19:30,NaN,NaN,NaN,NaN,NaN,CASTLE HILL AVENUE,WESTCHESTER AVENUE,NaN,...,NaN,NaN,NaN,NaN,80874,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913785,07/07/2012,23:10,NaN,NaN,40.727873,-73.929122,"(40.727873, -73.9291223)",NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3044674,SPORT UTILITY / STATION WAGON,UNKNOWN,NaN,NaN,NaN
913786,07/06/2012,0:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2867735,SPORT UTILITY / STATION WAGON,TAXI,NaN,NaN,NaN
913787,07/05/2012,15:43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2864071,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913788,07/05/2012,16:30,NaN,NaN,40.767894,-73.837995,"(40.7678942, -73.8379954)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3055606,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913789,07/04/2012,9:15,NaN,NaN,NaN,NaN,NaN,BAY PARKWAY,SHORE PARKWAY,NaN,...,NaN,NaN,NaN,NaN,121421,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913790,07/03/2012,0:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2896734,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913791,07/03/2012,12:35,BROOKLYN,11210.0,40.629166,-73.947326,"(40.6291662, -73.947326)",AVENUE I,NOSTRAND AVENUE,NaN,...,NaN,NaN,NaN,NaN,125685,VAN,NaN,NaN,NaN,NaN
913792,07/03/2012,16:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896732,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN,NaN
913793,07/03/2012,17:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3096749,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913794,07/03/2012,21:05,NaN,NaN,NaN,NaN,NaN,MURDOCK AVENUE,EAST 242 STREET,NaN,...,Unspecified,NaN,NaN,NaN,94897,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913795,07/02/2012,21:37,NaN,NaN,NaN,NaN,NaN,PELHAM PARKWAY SOUTH,HOLLAND AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,102728,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913796,07/01/2012,21:55,QUEENS,11368.0,40.753565,-73.870695,"(40.7535645, -73.8706949)",97 STREET,35 AVENUE,NaN,...,NaN,NaN,NaN,NaN,279645,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913797,07/01/2012,4:44,MANHATTAN,10001.0,40.746659,-73.990068,"(40.7466595, -73.9900681)",6 AVENUE,WEST 29 STREET,NaN,...,NaN,NaN,NaN,NaN,26084,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913798,07/01/2012,7:00,NaN,NaN,NaN,NaN,NaN,BEACH 54 STREET,ROCKAWAY BEACH BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,202242,PASSENGER VEHICLE,VAN,NaN,NaN,NaN
913799,07/01/2012,9:15,BROOKLYN,11233.0,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,NaN,...,Unspecified,NaN,NaN,NaN,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913800,07/01/2012,9:15,QUEENS,11421.0,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,NaN,...,Unspecified,NaN,NaN,NaN,203690,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913801,07/01/2012,9:15,QUEENS,11429.0,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,219394,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913802,07/01/2012,9:15,STATEN ISLAND,10310.0,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,284646,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN

In [14]:
import numpy as np

In [95]:
df_1 = df.replace(['Unspecified'], np.nan)

In [31]:
df_1

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,09/18/2016,19:09,QUEENS,11422.0,NaN,NaN,NaN,NaN,NaN,234-32 131 AVENUE,...,NaN,NaN,NaN,NaN,3522011,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
1,09/18/2016,19:09,BROOKLYN,11237.0,NaN,NaN,NaN,NaN,NaN,140 MORGAN AVENUE,...,Driver Inattention/Distraction,NaN,NaN,NaN,3522438,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
2,09/18/2016,1:09,MANHATTAN,10012.0,NaN,NaN,NaN,DELANCEY STREET,BOWERY,NaN,...,NaN,NaN,NaN,NaN,3523763,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
3,09/18/2016,1:09,NaN,NaN,40.862498,-73.934185,"(40.8624983, -73.9341848)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3524356,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
4,09/18/2016,20:09,BROOKLYN,11229.0,NaN,NaN,NaN,AVENUE W,PLUMB 1 STREET,NaN,...,NaN,NaN,NaN,NaN,3522651,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
5,09/18/2016,20:09,MANHATTAN,10003.0,NaN,NaN,NaN,NaN,NaN,355 BOWERY,...,NaN,NaN,NaN,NaN,3522315,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
6,08/25/2015,19:00,NaN,NaN,40.732941,-73.920382,"(40.7329414, -73.9203819)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3284922,PASSENGER VEHICLE,TAXI,NaN,NaN,NaN
7,07/27/2012,22:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2833714,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
8,05/17/2014,0:45,NaN,NaN,NaN,NaN,NaN,PENNSYLVANIA AVENUE,RIVERDALE AVENUE,NaN,...,NaN,NaN,NaN,NaN,336679,NaN,NaN,NaN,NaN,NaN
9,08/12/2016,1:08,QUEENS,11377.0,NaN,NaN,NaN,QUEENS BOULEVARD,69 STREET,NaN,...,NaN,NaN,NaN,NaN,3498919,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
10,08/12/2016,20:08,BRONX,10460.0,NaN,NaN,NaN,NaN,NaN,948 EAST 179 STREET,...,NaN,NaN,NaN,NaN,3499511,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
11,08/12/2016,20:08,BRONX,10466.0,NaN,NaN,NaN,EDENWALD AVENUE,BRUNER AVENUE,NaN,...,NaN,NaN,NaN,NaN,3500136,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
12,08/12/2016,20:08,BROOKLYN,11216.0,NaN,NaN,NaN,NaN,NaN,1323 FULTON STREET,...,NaN,NaN,NaN,NaN,3499591,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
13,08/12/2016,20:08,BROOKLYN,11226.0,NaN,NaN,NaN,NaN,NaN,500 OCEAN AVENUE,...,NaN,NaN,NaN,NaN,3501084,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
14,08/12/2016,20:08,BROOKLYN,11235.0,NaN,NaN,NaN,NaN,NaN,2805 AVENUE Y,...,NaN,NaN,NaN,NaN,3500227,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
15,09/18/2016,21:09,QUEENS,11420.0,NaN,NaN,NaN,NaN,NaN,114-18 120 STREET,...,NaN,NaN,NaN,NaN,3522320,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
16,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,ROGERS AVENUE,NaN,NaN,...,Other Vehicular,NaN,NaN,NaN,3523254,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN
17,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,UTOPIA PARKWAY,NaN,NaN,...,NaN,NaN,NaN,NaN,3523140,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
18,09/18/2016,22:09,BROOKLYN,11211.0,NaN,NaN,NaN,METROPOLITAN AVENUE,GARDNER AVENUE,NaN,...,NaN,NaN,NaN,NaN,3523286,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
19,08/12/2016,20:08,MANHATTAN,10036.0,NaN,NaN,NaN,10 AVENUE,WEST 41 STREET,NaN,...,NaN,NaN,NaN,NaN,3500791,SMALL COM VEH(4 TIRES),PASSENGER VEHICLE,NaN,NaN,NaN
20,08/12/2016,20:08,QUEENS,11101.0,NaN,NaN,NaN,44 DRIVE,10 STREET,NaN,...,NaN,NaN,NaN,NaN,3499705,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
21,08/12/2016,20:08,QUEENS,11377.0,NaN,NaN,NaN,NaN,NaN,69-10 34 AVENUE,...,NaN,NaN,NaN,NaN,3499764,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
22,08/12/2016,20:08,NaN,NaN,NaN,NaN,NaN,KINGS HIGHWAY,CLARENDON ROAD,NaN,...,NaN,NaN,NaN,NaN,3501024,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
23,05/03/2016,8:00,QUEENS,11385.0,40.707891,-73.909622,"(40.7078905, -73.9096224)",NaN,NaN,1934 GREENE AVENUE,...,NaN,NaN,NaN,NaN,3434031,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
24,05/03/2016,8:00,NaN,NaN,NaN,NaN,NaN,CROSSBAY BOULEVARD,SHORE PARKWAY,NaN,...,NaN,NaN,NaN,NaN,3434064,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
25,05/03/2016,8:09,BROOKLYN,11208.0,40.678828,-73.866171,"(40.6788277, -73.866171)",NaN,NaN,1168 LIBERTY AVENUE,...,NaN,NaN,NaN,NaN,3433897,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
26,05/03/2016,8:10,MANHATTAN,10031.0,40.830669,-73.944886,"(40.8306685, -73.9448864)",NaN,NaN,528 WEST 153 STREET,...,NaN,NaN,NaN,NaN,3434479,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
27,09/17/2016,13:09,STATEN ISLAND,10301.0,NaN,NaN,NaN,RICHMOND TERRACE,HAMILTON AVENUE,NaN,...,NaN,NaN,NaN,NaN,3524007,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
28,09/17/2016,13:09,NaN,NaN,NaN,NaN,NaN,MORNINGSTAR ROAD,WALKER STREET,NaN,...,NaN,NaN,NaN,NaN,3521752,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
29,09/17/2016,13:09,NaN,NaN,40.789540,-73.982252,"(40.7895396, -73.9822521)",NaN,NaN,NaN,...,Other Vehicular,Other Vehicular,Following Too Closely,NaN,3521917,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913773,07/11/2012,9:00,NaN,NaN,40.746107,-73.766791,"(40.746107, -73.7667908)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3078747,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913774,07/11/2012,9:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2912127,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913775,07/10/2012,12:00,NaN,NaN,NaN,NaN,NaN,ASTORIA BOULEVARD,31 STREET,NaN,...,NaN,NaN,NaN,NaN,272667,PASSENGER VEHICLE,PICK-UP TRUCK,NaN,NaN,NaN
913776,07/10/2012,18:00,NaN,NaN,NaN,NaN,NaN,KERMIT AVENUE,PARKINSON AVENUE,NaN,...,NaN,NaN,NaN,NaN,293261,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913777,07/10/2012,20:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2918666,PASSENGER VEHICLE,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN
913778,07/09/2012,13:45,NaN,NaN,NaN,NaN,NaN,PARK AVENUE,HALL STREET,NaN,...,NaN,NaN,NaN,NaN,191585,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913779,07/09/2012,4:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2879038,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913780,07/08/2012,22:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3016748,MOTORCYCLE,NaN,NaN,NaN,NaN
913781,07/08/2012,2:35,NaN,NaN,40.835486,-73.949394,"(40.8354859, -73.9493936)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2872826,OTHER,NaN,NaN,NaN,NaN
913782,07/07/2012,13:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3121385,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913783,07/07/2012,14:40,NaN,NaN,NaN,NaN,NaN,EAST 135 STREET,3 AVENUE,NaN,...,NaN,NaN,NaN,NaN,72655,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913784,07/07/2012,19:30,NaN,NaN,NaN,NaN,NaN,CASTLE HILL AVENUE,WESTCHESTER AVENUE,NaN,...,NaN,NaN,NaN,NaN,80874,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913785,07/07/2012,23:10,NaN,NaN,40.727873,-73.929122,"(40.727873, -73.9291223)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3044674,SPORT UTILITY / STATION WAGON,UNKNOWN,NaN,NaN,NaN
913786,07/06/2012,0:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2867735,SPORT UTILITY / STATION WAGON,TAXI,NaN,NaN,NaN
913787,07/05/2012,15:43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2864071,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913788,07/05/2012,16:30,NaN,NaN,40.767894,-73.837995,"(40.7678942, -73.8379954)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3055606,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913789,07/04/2012,9:15,NaN,NaN,NaN,NaN,NaN,BAY PARKWAY,SHORE PARKWAY,NaN,...,NaN,NaN,NaN,NaN,121421,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913790,07/03/2012,0:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896734,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913791,07/03/2012,12:35,BROOKLYN,11210.0,40.629166,-73.947326,"(40.6291662, -73.947326)",AVENUE I,NOSTRAND AVENUE,NaN,...,NaN,NaN,NaN,NaN,125685,VAN,NaN,NaN,NaN,NaN
913792,07/03/2012,16:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896732,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN,NaN
913793,07/03/2012,17:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3096749,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913794,07/03/2012,21:05,NaN,NaN,NaN,NaN,NaN,MURDOCK AVENUE,EAST 242 STREET,NaN,...,NaN,NaN,NaN,NaN,94897,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913795,07/02/2012,21:37,NaN,NaN,NaN,NaN,NaN,PELHAM PARKWAY SOUTH,HOLLAND AVENUE,NaN,...,NaN,NaN,NaN,NaN,102728,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913796,07/01/2012,21:55,QUEENS,11368.0,40.753565,-73.870695,"(40.7535645, -73.8706949)",97 STREET,35 AVENUE,NaN,...,NaN,NaN,NaN,NaN,279645,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913797,07/01/2012,4:44,MANHATTAN,10001.0,40.746659,-73.990068,"(40.7466595, -73.9900681)",6 AVENUE,WEST 29 STREET,NaN,...,NaN,NaN,NaN,NaN,26084,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913798,07/01/2012,7:00,NaN,NaN,NaN,NaN,NaN,BEACH 54 STREET,ROCKAWAY BEACH BOULEVARD,NaN,...,NaN,NaN,NaN,NaN,202242,PASSENGER VEHICLE,VAN,NaN,NaN,NaN
913799,07/01/2012,9:15,BROOKLYN,11233.0,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,NaN,...,NaN,NaN,NaN,NaN,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913800,07/01/2012,9:15,QUEENS,11421.0,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,NaN,...,NaN,NaN,NaN,NaN,203690,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913801,07/01/2012,9:15,QUEENS,11429.0,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,NaN,...,NaN,NaN,NaN,NaN,219394,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913802,07/01/2012,9:15,STATEN ISLAND,10310.0,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,NaN,...,NaN,NaN,NaN,NaN,284646,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN

In [65]:
# df_1[['ZIP CODE']] = df_1[['ZIP CODE']].fillna(int(0)).astype(int)

In [96]:
df_1.index = np.arange(1, len(df_1) + 1)

In [84]:
df_1

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
1,09/18/2016,19:09,QUEENS,11422.0,NaN,NaN,NaN,NaN,NaN,234-32 131 AVENUE,...,NaN,NaN,NaN,NaN,3522011,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
2,09/18/2016,19:09,BROOKLYN,11237.0,NaN,NaN,NaN,NaN,NaN,140 MORGAN AVENUE,...,Driver Inattention/Distraction,NaN,NaN,NaN,3522438,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
3,09/18/2016,1:09,MANHATTAN,10012.0,NaN,NaN,NaN,DELANCEY STREET,BOWERY,NaN,...,NaN,NaN,NaN,NaN,3523763,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
4,09/18/2016,1:09,NaN,NaN,40.862498,-73.934185,"(40.8624983, -73.9341848)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3524356,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
5,09/18/2016,20:09,BROOKLYN,11229.0,NaN,NaN,NaN,AVENUE W,PLUMB 1 STREET,NaN,...,NaN,NaN,NaN,NaN,3522651,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
6,09/18/2016,20:09,MANHATTAN,10003.0,NaN,NaN,NaN,NaN,NaN,355 BOWERY,...,NaN,NaN,NaN,NaN,3522315,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
7,08/25/2015,19:00,NaN,NaN,40.732941,-73.920382,"(40.7329414, -73.9203819)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3284922,PASSENGER VEHICLE,TAXI,NaN,NaN,NaN
8,07/27/2012,22:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2833714,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
9,05/17/2014,0:45,NaN,NaN,NaN,NaN,NaN,PENNSYLVANIA AVENUE,RIVERDALE AVENUE,NaN,...,NaN,NaN,NaN,NaN,336679,NaN,NaN,NaN,NaN,NaN
10,08/12/2016,1:08,QUEENS,11377.0,NaN,NaN,NaN,QUEENS BOULEVARD,69 STREET,NaN,...,NaN,NaN,NaN,NaN,3498919,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
11,08/12/2016,20:08,BRONX,10460.0,NaN,NaN,NaN,NaN,NaN,948 EAST 179 STREET,...,NaN,NaN,NaN,NaN,3499511,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
12,08/12/2016,20:08,BRONX,10466.0,NaN,NaN,NaN,EDENWALD AVENUE,BRUNER AVENUE,NaN,...,NaN,NaN,NaN,NaN,3500136,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
13,08/12/2016,20:08,BROOKLYN,11216.0,NaN,NaN,NaN,NaN,NaN,1323 FULTON STREET,...,NaN,NaN,NaN,NaN,3499591,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
14,08/12/2016,20:08,BROOKLYN,11226.0,NaN,NaN,NaN,NaN,NaN,500 OCEAN AVENUE,...,NaN,NaN,NaN,NaN,3501084,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
15,08/12/2016,20:08,BROOKLYN,11235.0,NaN,NaN,NaN,NaN,NaN,2805 AVENUE Y,...,NaN,NaN,NaN,NaN,3500227,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
16,09/18/2016,21:09,QUEENS,11420.0,NaN,NaN,NaN,NaN,NaN,114-18 120 STREET,...,NaN,NaN,NaN,NaN,3522320,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
17,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,ROGERS AVENUE,NaN,NaN,...,Other Vehicular,NaN,NaN,NaN,3523254,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN
18,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,UTOPIA PARKWAY,NaN,NaN,...,NaN,NaN,NaN,NaN,3523140,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
19,09/18/2016,22:09,BROOKLYN,11211.0,NaN,NaN,NaN,METROPOLITAN AVENUE,GARDNER AVENUE,NaN,...,NaN,NaN,NaN,NaN,3523286,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
20,08/12/2016,20:08,MANHATTAN,10036.0,NaN,NaN,NaN,10 AVENUE,WEST 41 STREET,NaN,...,NaN,NaN,NaN,NaN,3500791,SMALL COM VEH(4 TIRES),PASSENGER VEHICLE,NaN,NaN,NaN
21,08/12/2016,20:08,QUEENS,11101.0,NaN,NaN,NaN,44 DRIVE,10 STREET,NaN,...,NaN,NaN,NaN,NaN,3499705,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
22,08/12/2016,20:08,QUEENS,11377.0,NaN,NaN,NaN,NaN,NaN,69-10 34 AVENUE,...,NaN,NaN,NaN,NaN,3499764,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
23,08/12/2016,20:08,NaN,NaN,NaN,NaN,NaN,KINGS HIGHWAY,CLARENDON ROAD,NaN,...,NaN,NaN,NaN,NaN,3501024,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
24,05/03/2016,8:00,QUEENS,11385.0,40.707891,-73.909622,"(40.7078905, -73.9096224)",NaN,NaN,1934 GREENE AVENUE,...,NaN,NaN,NaN,NaN,3434031,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
25,05/03/2016,8:00,NaN,NaN,NaN,NaN,NaN,CROSSBAY BOULEVARD,SHORE PARKWAY,NaN,...,NaN,NaN,NaN,NaN,3434064,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
26,05/03/2016,8:09,BROOKLYN,11208.0,40.678828,-73.866171,"(40.6788277, -73.866171)",NaN,NaN,1168 LIBERTY AVENUE,...,NaN,NaN,NaN,NaN,3433897,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
27,05/03/2016,8:10,MANHATTAN,10031.0,40.830669,-73.944886,"(40.8306685, -73.9448864)",NaN,NaN,528 WEST 153 STREET,...,NaN,NaN,NaN,NaN,3434479,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
28,09/17/2016,13:09,STATEN ISLAND,10301.0,NaN,NaN,NaN,RICHMOND TERRACE,HAMILTON AVENUE,NaN,...,NaN,NaN,NaN,NaN,3524007,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
29,09/17/2016,13:09,NaN,NaN,NaN,NaN,NaN,MORNINGSTAR ROAD,WALKER STREET,NaN,...,NaN,NaN,NaN,NaN,3521752,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
30,09/17/2016,13:09,NaN,NaN,40.789540,-73.982252,"(40.7895396, -73.9822521)",NaN,NaN,NaN,...,Other Vehicular,Other Vehicular,Following Too Closely,NaN,3521917,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913774,07/11/2012,9:00,NaN,NaN,40.746107,-73.766791,"(40.746107, -73.7667908)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3078747,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913775,07/11/2012,9:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2912127,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913776,07/10/2012,12:00,NaN,NaN,NaN,NaN,NaN,ASTORIA BOULEVARD,31 STREET,NaN,...,NaN,NaN,NaN,NaN,272667,PASSENGER VEHICLE,PICK-UP TRUCK,NaN,NaN,NaN
913777,07/10/2012,18:00,NaN,NaN,NaN,NaN,NaN,KERMIT AVENUE,PARKINSON AVENUE,NaN,...,NaN,NaN,NaN,NaN,293261,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913778,07/10/2012,20:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2918666,PASSENGER VEHICLE,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN
913779,07/09/2012,13:45,NaN,NaN,NaN,NaN,NaN,PARK AVENUE,HALL STREET,NaN,...,NaN,NaN,NaN,NaN,191585,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913780,07/09/2012,4:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2879038,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913781,07/08/2012,22:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3016748,MOTORCYCLE,NaN,NaN,NaN,NaN
913782,07/08/2012,2:35,NaN,NaN,40.835486,-73.949394,"(40.8354859, -73.9493936)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2872826,OTHER,NaN,NaN,NaN,NaN
913783,07/07/2012,13:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3121385,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913784,07/07/2012,14:40,NaN,NaN,NaN,NaN,NaN,EAST 135 STREET,3 AVENUE,NaN,...,NaN,NaN,NaN,NaN,72655,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913785,07/07/2012,19:30,NaN,NaN,NaN,NaN,NaN,CASTLE HILL AVENUE,WESTCHESTER AVENUE,NaN,...,NaN,NaN,NaN,NaN,80874,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913786,07/07/2012,23:10,NaN,NaN,40.727873,-73.929122,"(40.727873, -73.9291223)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3044674,SPORT UTILITY / STATION WAGON,UNKNOWN,NaN,NaN,NaN
913787,07/06/2012,0:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2867735,SPORT UTILITY / STATION WAGON,TAXI,NaN,NaN,NaN
913788,07/05/2012,15:43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2864071,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913789,07/05/2012,16:30,NaN,NaN,40.767894,-73.837995,"(40.7678942, -73.8379954)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3055606,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913790,07/04/2012,9:15,NaN,NaN,NaN,NaN,NaN,BAY PARKWAY,SHORE PARKWAY,NaN,...,NaN,NaN,NaN,NaN,121421,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913791,07/03/2012,0:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896734,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913792,07/03/2012,12:35,BROOKLYN,11210.0,40.629166,-73.947326,"(40.6291662, -73.947326)",AVENUE I,NOSTRAND AVENUE,NaN,...,NaN,NaN,NaN,NaN,125685,VAN,NaN,NaN,NaN,NaN
913793,07/03/2012,16:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896732,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN,NaN
913794,07/03/2012,17:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3096749,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913795,07/03/2012,21:05,NaN,NaN,NaN,NaN,NaN,MURDOCK AVENUE,EAST 242 STREET,NaN,...,NaN,NaN,NaN,NaN,94897,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913796,07/02/2012,21:37,NaN,NaN,NaN,NaN,NaN,PELHAM PARKWAY SOUTH,HOLLAND AVENUE,NaN,...,NaN,NaN,NaN,NaN,102728,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913797,07/01/2012,21:55,QUEENS,11368.0,40.753565,-73.870695,"(40.7535645, -73.8706949)",97 STREET,35 AVENUE,NaN,...,NaN,NaN,NaN,NaN,279645,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913798,07/01/2012,4:44,MANHATTAN,10001.0,40.746659,-73.990068,"(40.7466595, -73.9900681)",6 AVENUE,WEST 29 STREET,NaN,...,NaN,NaN,NaN,NaN,26084,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913799,07/01/2012,7:00,NaN,NaN,NaN,NaN,NaN,BEACH 54 STREET,ROCKAWAY BEACH BOULEVARD,NaN,...,NaN,NaN,NaN,NaN,202242,PASSENGER VEHICLE,VAN,NaN,NaN,NaN
913800,07/01/2012,9:15,BROOKLYN,11233.0,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,NaN,...,NaN,NaN,NaN,NaN,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913801,07/01/2012,9:15,QUEENS,11421.0,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,NaN,...,NaN,NaN,NaN,NaN,203690,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913802,07/01/2012,9:15,QUEENS,11429.0,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,NaN,...,NaN,NaN,NaN,NaN,219394,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913803,07/01/2012,9:15,STATEN ISLAND,10310.0,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,NaN,...,NaN,NaN,NaN,NaN,284646,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN

In [85]:
df.ix[1]

DATE                                                 09/18/2016
TIME                                                      19:09
BOROUGH                                                BROOKLYN
ZIP CODE                                                  11237
LATITUDE                                                    NaN
LONGITUDE                                                   NaN
LOCATION                                                    NaN
ON STREET NAME                                              NaN
CROSS STREET NAME                                           NaN
OFF STREET NAME                         140       MORGAN AVENUE
NUMBER OF PERSONS INJURED                                     2
NUMBER OF PERSONS KILLED                                      0
NUMBER OF PEDESTRIANS INJURED                                 0
NUMBER OF PEDESTRIANS KILLED                                  0
NUMBER OF CYCLIST INJURED                                     0
NUMBER OF CYCLIST KILLED                                      0
NUMBER OF MOTORIST INJURED                                    2
NUMBER OF MOTORIST KILLED                                     0
CONTRIBUTING FACTOR VEHICLE 1    Driver Inattention/Distraction
CONTRIBUTING FACTOR VEHICLE 2    Driver Inattention/Distraction
CONTRIBUTING FACTOR VEHICLE 3                               NaN
CONTRIBUTING FACTOR VEHICLE 4                               NaN
CONTRIBUTING FACTOR VEHICLE 5                               NaN
UNIQUE KEY                                              3522438
VEHICLE TYPE CODE 1                                        TAXI
VEHICLE TYPE CODE 2               SPORT UTILITY / STATION WAGON
VEHICLE TYPE CODE 3                                         NaN
VEHICLE TYPE CODE 4                                         NaN
VEHICLE TYPE CODE 5                                         NaN
Name: 1, dtype: object

In [86]:
df_1.ix[[1]]

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
1,09/18/2016,19:09,QUEENS,11422.0,NaN,NaN,NaN,NaN,NaN,234-32 131 AVENUE,...,NaN,NaN,NaN,NaN,3522011,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN

In [87]:
df_1.loc[[1]]

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
1,09/18/2016,19:09,QUEENS,11422.0,NaN,NaN,NaN,NaN,NaN,234-32 131 AVENUE,...,NaN,NaN,NaN,NaN,3522011,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN

In [88]:
df_1.loc[1]

DATE                                                09/18/2016
TIME                                                     19:09
BOROUGH                                                 QUEENS
ZIP CODE                                                 11422
LATITUDE                                                   NaN
LONGITUDE                                                  NaN
LOCATION                                                   NaN
ON STREET NAME                                             NaN
CROSS STREET NAME                                          NaN
OFF STREET NAME                           234-32    131 AVENUE
NUMBER OF PERSONS INJURED                                    0
NUMBER OF PERSONS KILLED                                     0
NUMBER OF PEDESTRIANS INJURED                                0
NUMBER OF PEDESTRIANS KILLED                                 0
NUMBER OF CYCLIST INJURED                                    0
NUMBER OF CYCLIST KILLED                                     0
NUMBER OF MOTORIST INJURED                                   0
NUMBER OF MOTORIST KILLED                                    0
CONTRIBUTING FACTOR VEHICLE 1                              NaN
CONTRIBUTING FACTOR VEHICLE 2                              NaN
CONTRIBUTING FACTOR VEHICLE 3                              NaN
CONTRIBUTING FACTOR VEHICLE 4                              NaN
CONTRIBUTING FACTOR VEHICLE 5                              NaN
UNIQUE KEY                                             3522011
VEHICLE TYPE CODE 1              SPORT UTILITY / STATION WAGON
VEHICLE TYPE CODE 2                                        NaN
VEHICLE TYPE CODE 3                                        NaN
VEHICLE TYPE CODE 4                                        NaN
VEHICLE TYPE CODE 5                                        NaN
Name: 1, dtype: object

In [89]:
df_1.iloc[[1]]

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
2,09/18/2016,19:09,BROOKLYN,11237.0,NaN,NaN,NaN,NaN,NaN,140 MORGAN AVENUE,...,Driver Inattention/Distraction,NaN,NaN,NaN,3522438,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN

In [90]:
df_1.iloc[1]

DATE                                                 09/18/2016
TIME                                                      19:09
BOROUGH                                                BROOKLYN
ZIP CODE                                                  11237
LATITUDE                                                    NaN
LONGITUDE                                                   NaN
LOCATION                                                    NaN
ON STREET NAME                                              NaN
CROSS STREET NAME                                           NaN
OFF STREET NAME                         140       MORGAN AVENUE
NUMBER OF PERSONS INJURED                                     2
NUMBER OF PERSONS KILLED                                      0
NUMBER OF PEDESTRIANS INJURED                                 0
NUMBER OF PEDESTRIANS KILLED                                  0
NUMBER OF CYCLIST INJURED                                     0
NUMBER OF CYCLIST KILLED                                      0
NUMBER OF MOTORIST INJURED                                    2
NUMBER OF MOTORIST KILLED                                     0
CONTRIBUTING FACTOR VEHICLE 1    Driver Inattention/Distraction
CONTRIBUTING FACTOR VEHICLE 2    Driver Inattention/Distraction
CONTRIBUTING FACTOR VEHICLE 3                               NaN
CONTRIBUTING FACTOR VEHICLE 4                               NaN
CONTRIBUTING FACTOR VEHICLE 5                               NaN
UNIQUE KEY                                              3522438
VEHICLE TYPE CODE 1                                        TAXI
VEHICLE TYPE CODE 2               SPORT UTILITY / STATION WAGON
VEHICLE TYPE CODE 3                                         NaN
VEHICLE TYPE CODE 4                                         NaN
VEHICLE TYPE CODE 5                                         NaN
Name: 2, dtype: object

In [97]:
df_1.sort_values(['BOROUGH', 'ZIP CODE'])

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
957,08/01/2016,10:08,BRONX,10451.0,40.816120,-73.926629,"(40.8161196, -73.9266288)",EAST 144 STREET,PARK AVENUE,NaN,...,NaN,NaN,NaN,NaN,3532773,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
1651,09/30/2016,17:09,BRONX,10451.0,NaN,NaN,NaN,MORRIS AVENUE,EAST 151 STREET,NaN,...,NaN,NaN,NaN,NaN,3531433,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
1962,09/30/2016,9:09,BRONX,10451.0,NaN,NaN,NaN,CANAL PLACE,EAST 138 STREET,NaN,...,NaN,NaN,NaN,NaN,3531432,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
2053,09/29/2016,11:09,BRONX,10451.0,NaN,NaN,NaN,RIVER AVENUE,EAST 161 STREET,NaN,...,NaN,NaN,NaN,NaN,3529816,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
2265,07/14/2016,21:07,BRONX,10451.0,NaN,NaN,NaN,EAST 149 STREET,GERARD AVENUE,NaN,...,NaN,NaN,NaN,NaN,3480300,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
2452,09/29/2016,9:09,BRONX,10451.0,NaN,NaN,NaN,COLLEGE AVENUE,EAST 148 STREET,NaN,...,NaN,NaN,NaN,NaN,3530312,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
2478,08/20/2016,23:08,BRONX,10451.0,NaN,NaN,NaN,EAST 152 STREET,COURTLANDT AVENUE,NaN,...,NaN,NaN,NaN,NaN,3504450,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
2653,10/25/2016,11:10,BRONX,10451.0,40.825116,-73.925401,"(40.825116, -73.9254012)",WALTON AVENUE,EAST 157 STREET,NaN,...,NaN,NaN,NaN,NaN,3547722,TAXI,NaN,NaN,NaN,NaN
2789,10/25/2016,18:10,BRONX,10451.0,40.813746,-73.931393,"(40.8137456, -73.9313928)",EXTERIOR STREET,EAST 138 STREET,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,3547219,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
2825,09/27/2016,10:09,BRONX,10451.0,NaN,NaN,NaN,GRAND CONCOURSE,EAST 161 STREET,NaN,...,NaN,NaN,NaN,NaN,3528289,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
2831,10/25/2016,22:10,BRONX,10451.0,40.818810,-73.928277,"(40.8188104, -73.9282769)",WALTON AVENUE,EAST 149 STREET,NaN,...,NaN,NaN,NaN,NaN,3547841,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
2986,10/08/2015,7:58,BRONX,10451.0,40.824708,-73.915516,"(40.8247084, -73.9155159)",EAST 161 STREET,COURTLANDT AVENUE,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,3311755,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
3056,10/24/2016,14:10,BRONX,10451.0,40.822306,-73.914843,"(40.8223063, -73.9148433)",EAST 158 STREET,MELROSE AVENUE,NaN,...,NaN,NaN,NaN,NaN,3547016,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
3097,09/27/2016,18:09,BRONX,10451.0,NaN,NaN,NaN,NaN,NaN,200 EAST 135 STREET,...,NaN,NaN,NaN,NaN,3529222,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
3260,08/10/2016,11:08,BRONX,10451.0,NaN,NaN,NaN,EAST 149 STREET,COURTLANDT AVENUE,NaN,...,NaN,NaN,NaN,NaN,3497944,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
3399,10/23/2016,16:10,BRONX,10451.0,40.824061,-73.928141,"(40.824061, -73.9281412)",RIVER AVENUE,EAST 153 STREET,NaN,...,NaN,NaN,NaN,NaN,3546374,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
3573,09/26/2016,8:09,BRONX,10451.0,NaN,NaN,NaN,MORRIS AVENUE,EAST 161 STREET,NaN,...,NaN,NaN,NaN,NaN,3527676,PASSENGER VEHICLE,TAXI,NaN,NaN,NaN
3781,10/14/2016,17:10,BRONX,10451.0,40.813666,-73.931237,"(40.8136659, -73.9312375)",MAJOR DEEGAN EXPRESSWAY,EAST 138 STREET,NaN,...,Following Too Closely,Following Too Closely,NaN,NaN,3541541,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
3964,09/23/2016,15:09,BRONX,10451.0,NaN,NaN,NaN,NaN,NaN,837 WASHINGTON AVENUE,...,Unsafe Speed,NaN,NaN,NaN,3526099,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN
4190,09/21/2016,18:09,BRONX,10451.0,NaN,NaN,NaN,GRAND CONCOURSE,EAST 153 STREET,NaN,...,NaN,NaN,NaN,NaN,3524719,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
4285,07/30/2015,11:15,BRONX,10451.0,40.828602,-73.921748,"(40.8286021, -73.9217477)",GRAND CONCOURSE,EAST 163 STREET,NaN,...,NaN,NaN,NaN,NaN,3268292,VAN,PASSENGER VEHICLE,NaN,NaN,NaN
4298,09/05/2016,16:09,BRONX,10451.0,NaN,NaN,NaN,NaN,NaN,3237 3 AVENUE,...,NaN,NaN,NaN,NaN,3513852,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
4394,09/19/2016,22:09,BRONX,10451.0,NaN,NaN,NaN,GRAND CONCOURSE,EAST 161 STREET,NaN,...,NaN,NaN,NaN,NaN,3523454,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
5033,07/27/2016,16:23,BRONX,10451.0,40.817388,-73.922758,"(40.8173878, -73.922758)",EAST 149 STREET,MORRIS AVENUE,NaN,...,NaN,NaN,NaN,NaN,3489320,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
5185,09/21/2016,23:09,BRONX,10451.0,NaN,NaN,NaN,MORRIS AVENUE,EAST 150 STREET,NaN,...,NaN,NaN,NaN,NaN,3525112,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
5343,09/05/2016,1:09,BRONX,10451.0,NaN,NaN,NaN,RIDER AVENUE,EAST 139 STREET,NaN,...,NaN,NaN,NaN,NaN,3513849,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
5494,09/04/2016,20:09,BRONX,10451.0,NaN,NaN,NaN,EAST 158 STREET,CONCOURSE VILLAGE EAST,NaN,...,NaN,NaN,NaN,NaN,3513386,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
5993,09/02/2016,18:09,BRONX,10451.0,NaN,NaN,NaN,EXTERIOR STREET,EAST 150 STREET,NaN,...,NaN,NaN,NaN,NaN,3513377,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
6874,08/04/2016,10:08,BRONX,10451.0,NaN,NaN,NaN,NaN,NaN,304 EAST 156 STREET,...,NaN,NaN,NaN,NaN,3493984,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
7085,08/14/2016,4:08,BRONX,10451.0,NaN,NaN,NaN,NaN,NaN,598 GRAND CONCOURSE,...,NaN,NaN,NaN,NaN,3499489,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913767,07/15/2012,7:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896761,LIVERY VEHICLE,VAN,NaN,NaN,NaN
913768,07/14/2012,3:40,NaN,NaN,NaN,NaN,NaN,STEINWAY STREET,ASTORIA BOULEVARD,NaN,...,NaN,NaN,NaN,NaN,272708,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913769,07/13/2012,14:50,NaN,NaN,NaN,NaN,NaN,EASTCHESTER ROAD,PELHAM PARKWAY,NaN,...,NaN,NaN,NaN,NaN,102788,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913770,07/13/2012,6:51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3096760,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913771,07/12/2012,13:25,NaN,NaN,NaN,NaN,NaN,EAST 149 STREET,EXTERIOR STREET,NaN,...,Brakes Defective,NaN,NaN,NaN,72675,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913772,07/12/2012,15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PARKING LOT OF 356 BAYCHESTER AVENUE,...,NaN,NaN,NaN,NaN,88623,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913773,07/12/2012,7:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2988038,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913774,07/11/2012,9:00,NaN,NaN,40.746107,-73.766791,"(40.746107, -73.7667908)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3078747,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913775,07/11/2012,9:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2912127,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913776,07/10/2012,12:00,NaN,NaN,NaN,NaN,NaN,ASTORIA BOULEVARD,31 STREET,NaN,...,NaN,NaN,NaN,NaN,272667,PASSENGER VEHICLE,PICK-UP TRUCK,NaN,NaN,NaN
913777,07/10/2012,18:00,NaN,NaN,NaN,NaN,NaN,KERMIT AVENUE,PARKINSON AVENUE,NaN,...,NaN,NaN,NaN,NaN,293261,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913778,07/10/2012,20:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2918666,PASSENGER VEHICLE,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN
913779,07/09/2012,13:45,NaN,NaN,NaN,NaN,NaN,PARK AVENUE,HALL STREET,NaN,...,NaN,NaN,NaN,NaN,191585,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913780,07/09/2012,4:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2879038,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913781,07/08/2012,22:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3016748,MOTORCYCLE,NaN,NaN,NaN,NaN
913782,07/08/2012,2:35,NaN,NaN,40.835486,-73.949394,"(40.8354859, -73.9493936)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2872826,OTHER,NaN,NaN,NaN,NaN
913783,07/07/2012,13:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3121385,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913784,07/07/2012,14:40,NaN,NaN,NaN,NaN,NaN,EAST 135 STREET,3 AVENUE,NaN,...,NaN,NaN,NaN,NaN,72655,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913785,07/07/2012,19:30,NaN,NaN,NaN,NaN,NaN,CASTLE HILL AVENUE,WESTCHESTER AVENUE,NaN,...,NaN,NaN,NaN,NaN,80874,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913786,07/07/2012,23:10,NaN,NaN,40.727873,-73.929122,"(40.727873, -73.9291223)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3044674,SPORT UTILITY / STATION WAGON,UNKNOWN,NaN,NaN,NaN
913787,07/06/2012,0:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2867735,SPORT UTILITY / STATION WAGON,TAXI,NaN,NaN,NaN
913788,07/05/2012,15:43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2864071,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913789,07/05/2012,16:30,NaN,NaN,40.767894,-73.837995,"(40.7678942, -73.8379954)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3055606,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913790,07/04/2012,9:15,NaN,NaN,NaN,NaN,NaN,BAY PARKWAY,SHORE PARKWAY,NaN,...,NaN,NaN,NaN,NaN,121421,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913791,07/03/2012,0:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896734,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913793,07/03/2012,16:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896732,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN,NaN
913794,07/03/2012,17:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3096749,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913795,07/03/2012,21:05,NaN,NaN,NaN,NaN,NaN,MURDOCK AVENUE,EAST 242 STREET,NaN,...,NaN,NaN,NaN,NaN,94897,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913796,07/02/2012,21:37,NaN,NaN,NaN,NaN,NaN,PELHAM PARKWAY SOUTH,HOLLAND AVENUE,NaN,...,NaN,NaN,NaN,NaN,102728,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913799,07/01/2012,7:00,NaN,NaN,NaN,NaN,NaN,BEACH 54 STREET,ROCKAWAY BEACH BOULEVARD,NaN,...,NaN,NaN,NaN,NaN,202242,PASSENGER VEHICLE,VAN,NaN,NaN,NaN

In [132]:
#gp_1 = df_1.groupby(['ZIP CODE'])

In [133]:
#gp_zipcode = gp_1['ZIP CODE']

In [134]:
#zipcode_count = gp_zipcode.agg(['count'])

In [146]:
#type(zipcode_count)

pandas.core.frame.DataFrame

In [153]:
zipcode_count = df_1.groupby(['ZIP CODE'])['ZIP CODE'].count()

In [154]:
type(zipcode_count)

pandas.core.series.Series

In [155]:
zipcode_count

ZIP CODE
10000.0      51
10001.0    8729
10002.0    7434
10003.0    5747
10004.0    1277
10005.0     741
10006.0     870
10007.0    2236
10009.0    3306
10010.0    4477
10011.0    6057
10012.0    4466
10013.0    7931
10014.0    3772
10016.0    9794
10017.0    6177
10018.0    6636
10019.0    9482
10020.0     440
10021.0    3696
10022.0    9624
10023.0    4313
10024.0    3786
10025.0    4395
10026.0    1923
10027.0    4913
10028.0    2681
10029.0    5630
10030.0    1973
10031.0    2823
           ...
11385.0    7576
11411.0    1845
11412.0    2960
11413.0    4417
11414.0    1856
11415.0    1273
11416.0    2114
11417.0    3225
11418.0    3026
11419.0    3904
11420.0    4208
11421.0    2561
11422.0    3979
11423.0    2491
11426.0    1293
11427.0    1751
11428.0    1628
11429.0    2021
11430.0      81
11432.0    5023
11433.0    3213
11434.0    7174
11435.0    4132
11436.0    1444
11691.0    3117
11692.0     811
11693.0     839
11694.0     931
11695.0      10
11697.0      83
Name: ZIP CODE, dtype: int64

In [143]:
borough_count = df_1.groupby(['BOROUGH'])['BOROUGH'].count()

In [144]:
borough_count

BOROUGH
BRONX             88230
BROOKLYN         208521
MANHATTAN        176856
QUEENS           176260
STATEN ISLAND     31692
Name: BOROUGH, dtype: int64

In [145]:
type(borough_count)

pandas.core.series.Series

In [158]:
mapping = df_1.groupby(['BOROUGH'])['BOROUGH', 'ZIP CODE']

In [159]:
mapping

In [107]:
list(gp)

[('LATITUDE', 'sum'),
 ('LATITUDE', 'mean'),
 ('LATITUDE', 'std'),
 ('LONGITUDE', 'sum'),
 ('LONGITUDE', 'mean'),
 ('LONGITUDE', 'std'),
 ('NUMBER OF PERSONS INJURED', 'sum'),
 ('NUMBER OF PERSONS INJURED', 'mean'),
 ('NUMBER OF PERSONS INJURED', 'std'),
 ('NUMBER OF PERSONS KILLED', 'sum'),
 ('NUMBER OF PERSONS KILLED', 'mean'),
 ('NUMBER OF PERSONS KILLED', 'std'),
 ('NUMBER OF PEDESTRIANS INJURED', 'sum'),
 ('NUMBER OF PEDESTRIANS INJURED', 'mean'),
 ('NUMBER OF PEDESTRIANS INJURED', 'std'),
 ('NUMBER OF PEDESTRIANS KILLED', 'sum'),
 ('NUMBER OF PEDESTRIANS KILLED', 'mean'),
 ('NUMBER OF PEDESTRIANS KILLED', 'std'),
 ('NUMBER OF CYCLIST INJURED', 'sum'),
 ('NUMBER OF CYCLIST INJURED', 'mean'),
 ('NUMBER OF CYCLIST INJURED', 'std'),
 ('NUMBER OF CYCLIST KILLED', 'sum'),
 ('NUMBER OF CYCLIST KILLED', 'mean'),
 ('NUMBER OF CYCLIST KILLED', 'std'),
 ('NUMBER OF MOTORIST INJURED', 'sum'),
 ('NUMBER OF MOTORIST INJURED', 'mean'),
 ('NUMBER OF MOTORIST INJURED', 'std'),
 ('NUMBER OF MOTORIST KILLED', 'sum'),
 ('NUMBER OF MOTORIST KILLED', 'mean'),
 ('NUMBER OF MOTORIST KILLED', 'std'),
 ('UNIQUE KEY', 'sum'),
 ('UNIQUE KEY', 'mean'),
 ('UNIQUE KEY', 'std')]