In [5]:
import pandas as pd

In [6]:
filepath = "/Users/weiweixu/Downloads/2016 Fall/Programming for Data Science/NYPD_Motor_Vehicle_Collisions.csv"

# change to your own path

In [7]:
df = pd.read_csv(filepath)

In [8]:
df

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,09/18/2016,19:09,QUEENS,11422.0,NaN,NaN,NaN,NaN,NaN,234-32 131 AVENUE,...,NaN,NaN,NaN,NaN,3522011,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
1,09/18/2016,19:09,BROOKLYN,11237.0,NaN,NaN,NaN,NaN,NaN,140 MORGAN AVENUE,...,Driver Inattention/Distraction,NaN,NaN,NaN,3522438,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
2,09/18/2016,1:09,MANHATTAN,10012.0,NaN,NaN,NaN,DELANCEY STREET,BOWERY,NaN,...,Unspecified,NaN,NaN,NaN,3523763,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
3,09/18/2016,1:09,NaN,NaN,40.862498,-73.934185,"(40.8624983, -73.9341848)",NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3524356,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
4,09/18/2016,20:09,BROOKLYN,11229.0,NaN,NaN,NaN,AVENUE W,PLUMB 1 STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,3522651,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
5,09/18/2016,20:09,MANHATTAN,10003.0,NaN,NaN,NaN,NaN,NaN,355 BOWERY,...,Unspecified,NaN,NaN,NaN,3522315,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
6,08/25/2015,19:00,NaN,NaN,40.732941,-73.920382,"(40.7329414, -73.9203819)",NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3284922,PASSENGER VEHICLE,TAXI,NaN,NaN,NaN
7,07/27/2012,22:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2833714,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
8,05/17/2014,0:45,NaN,NaN,NaN,NaN,NaN,PENNSYLVANIA AVENUE,RIVERDALE AVENUE,NaN,...,NaN,NaN,NaN,NaN,336679,NaN,NaN,NaN,NaN,NaN
9,08/12/2016,1:08,QUEENS,11377.0,NaN,NaN,NaN,QUEENS BOULEVARD,69 STREET,NaN,...,Unspecified,NaN,NaN,NaN,3498919,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
10,08/12/2016,20:08,BRONX,10460.0,NaN,NaN,NaN,NaN,NaN,948 EAST 179 STREET,...,Unspecified,NaN,NaN,NaN,3499511,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
11,08/12/2016,20:08,BRONX,10466.0,NaN,NaN,NaN,EDENWALD AVENUE,BRUNER AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3500136,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
12,08/12/2016,20:08,BROOKLYN,11216.0,NaN,NaN,NaN,NaN,NaN,1323 FULTON STREET,...,Unspecified,NaN,NaN,NaN,3499591,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
13,08/12/2016,20:08,BROOKLYN,11226.0,NaN,NaN,NaN,NaN,NaN,500 OCEAN AVENUE,...,Unspecified,NaN,NaN,NaN,3501084,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
14,08/12/2016,20:08,BROOKLYN,11235.0,NaN,NaN,NaN,NaN,NaN,2805 AVENUE Y,...,Unspecified,NaN,NaN,NaN,3500227,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
15,09/18/2016,21:09,QUEENS,11420.0,NaN,NaN,NaN,NaN,NaN,114-18 120 STREET,...,Unspecified,NaN,NaN,NaN,3522320,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
16,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,ROGERS AVENUE,NaN,NaN,...,Other Vehicular,Unspecified,NaN,NaN,3523254,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN
17,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,UTOPIA PARKWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3523140,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
18,09/18/2016,22:09,BROOKLYN,11211.0,NaN,NaN,NaN,METROPOLITAN AVENUE,GARDNER AVENUE,NaN,...,NaN,NaN,NaN,NaN,3523286,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
19,08/12/2016,20:08,MANHATTAN,10036.0,NaN,NaN,NaN,10 AVENUE,WEST 41 STREET,NaN,...,Unspecified,NaN,NaN,NaN,3500791,SMALL COM VEH(4 TIRES),PASSENGER VEHICLE,NaN,NaN,NaN
20,08/12/2016,20:08,QUEENS,11101.0,NaN,NaN,NaN,44 DRIVE,10 STREET,NaN,...,Unspecified,NaN,NaN,NaN,3499705,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
21,08/12/2016,20:08,QUEENS,11377.0,NaN,NaN,NaN,NaN,NaN,69-10 34 AVENUE,...,Unspecified,NaN,NaN,NaN,3499764,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
22,08/12/2016,20:08,NaN,NaN,NaN,NaN,NaN,KINGS HIGHWAY,CLARENDON ROAD,NaN,...,Unspecified,NaN,NaN,NaN,3501024,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
23,05/03/2016,8:00,QUEENS,11385.0,40.707891,-73.909622,"(40.7078905, -73.9096224)",NaN,NaN,1934 GREENE AVENUE,...,Unspecified,NaN,NaN,NaN,3434031,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
24,05/03/2016,8:00,NaN,NaN,NaN,NaN,NaN,CROSSBAY BOULEVARD,SHORE PARKWAY,NaN,...,Unspecified,NaN,NaN,NaN,3434064,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
25,05/03/2016,8:09,BROOKLYN,11208.0,40.678828,-73.866171,"(40.6788277, -73.866171)",NaN,NaN,1168 LIBERTY AVENUE,...,NaN,NaN,NaN,NaN,3433897,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
26,05/03/2016,8:10,MANHATTAN,10031.0,40.830669,-73.944886,"(40.8306685, -73.9448864)",NaN,NaN,528 WEST 153 STREET,...,Unspecified,NaN,NaN,NaN,3434479,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
27,09/17/2016,13:09,STATEN ISLAND,10301.0,NaN,NaN,NaN,RICHMOND TERRACE,HAMILTON AVENUE,NaN,...,NaN,NaN,NaN,NaN,3524007,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
28,09/17/2016,13:09,NaN,NaN,NaN,NaN,NaN,MORNINGSTAR ROAD,WALKER STREET,NaN,...,NaN,NaN,NaN,NaN,3521752,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
29,09/17/2016,13:09,NaN,NaN,40.789540,-73.982252,"(40.7895396, -73.9822521)",NaN,NaN,NaN,...,Other Vehicular,Other Vehicular,Following Too Closely,NaN,3521917,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913773,07/11/2012,9:00,NaN,NaN,40.746107,-73.766791,"(40.746107, -73.7667908)",NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3078747,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913774,07/11/2012,9:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2912127,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913775,07/10/2012,12:00,NaN,NaN,NaN,NaN,NaN,ASTORIA BOULEVARD,31 STREET,NaN,...,Unspecified,NaN,NaN,NaN,272667,PASSENGER VEHICLE,PICK-UP TRUCK,NaN,NaN,NaN
913776,07/10/2012,18:00,NaN,NaN,NaN,NaN,NaN,KERMIT AVENUE,PARKINSON AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,293261,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913777,07/10/2012,20:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2918666,PASSENGER VEHICLE,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN
913778,07/09/2012,13:45,NaN,NaN,NaN,NaN,NaN,PARK AVENUE,HALL STREET,NaN,...,NaN,NaN,NaN,NaN,191585,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913779,07/09/2012,4:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2879038,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913780,07/08/2012,22:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3016748,MOTORCYCLE,NaN,NaN,NaN,NaN
913781,07/08/2012,2:35,NaN,NaN,40.835486,-73.949394,"(40.8354859, -73.9493936)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2872826,OTHER,NaN,NaN,NaN,NaN
913782,07/07/2012,13:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3121385,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913783,07/07/2012,14:40,NaN,NaN,NaN,NaN,NaN,EAST 135 STREET,3 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,72655,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913784,07/07/2012,19:30,NaN,NaN,NaN,NaN,NaN,CASTLE HILL AVENUE,WESTCHESTER AVENUE,NaN,...,NaN,NaN,NaN,NaN,80874,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913785,07/07/2012,23:10,NaN,NaN,40.727873,-73.929122,"(40.727873, -73.9291223)",NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3044674,SPORT UTILITY / STATION WAGON,UNKNOWN,NaN,NaN,NaN
913786,07/06/2012,0:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2867735,SPORT UTILITY / STATION WAGON,TAXI,NaN,NaN,NaN
913787,07/05/2012,15:43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2864071,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913788,07/05/2012,16:30,NaN,NaN,40.767894,-73.837995,"(40.7678942, -73.8379954)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3055606,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913789,07/04/2012,9:15,NaN,NaN,NaN,NaN,NaN,BAY PARKWAY,SHORE PARKWAY,NaN,...,NaN,NaN,NaN,NaN,121421,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913790,07/03/2012,0:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2896734,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913791,07/03/2012,12:35,BROOKLYN,11210.0,40.629166,-73.947326,"(40.6291662, -73.947326)",AVENUE I,NOSTRAND AVENUE,NaN,...,NaN,NaN,NaN,NaN,125685,VAN,NaN,NaN,NaN,NaN
913792,07/03/2012,16:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896732,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN,NaN
913793,07/03/2012,17:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3096749,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913794,07/03/2012,21:05,NaN,NaN,NaN,NaN,NaN,MURDOCK AVENUE,EAST 242 STREET,NaN,...,Unspecified,NaN,NaN,NaN,94897,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913795,07/02/2012,21:37,NaN,NaN,NaN,NaN,NaN,PELHAM PARKWAY SOUTH,HOLLAND AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,102728,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913796,07/01/2012,21:55,QUEENS,11368.0,40.753565,-73.870695,"(40.7535645, -73.8706949)",97 STREET,35 AVENUE,NaN,...,NaN,NaN,NaN,NaN,279645,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913797,07/01/2012,4:44,MANHATTAN,10001.0,40.746659,-73.990068,"(40.7466595, -73.9900681)",6 AVENUE,WEST 29 STREET,NaN,...,NaN,NaN,NaN,NaN,26084,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913798,07/01/2012,7:00,NaN,NaN,NaN,NaN,NaN,BEACH 54 STREET,ROCKAWAY BEACH BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,202242,PASSENGER VEHICLE,VAN,NaN,NaN,NaN
913799,07/01/2012,9:15,BROOKLYN,11233.0,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,NaN,...,Unspecified,NaN,NaN,NaN,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913800,07/01/2012,9:15,QUEENS,11421.0,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,NaN,...,Unspecified,NaN,NaN,NaN,203690,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913801,07/01/2012,9:15,QUEENS,11429.0,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,219394,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913802,07/01/2012,9:15,STATEN ISLAND,10310.0,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,284646,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN

In [9]:
import numpy as np

In [10]:
df_1 = df.replace(['Unspecified'], np.nan)

In [11]:
df_1

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,09/18/2016,19:09,QUEENS,11422.0,NaN,NaN,NaN,NaN,NaN,234-32 131 AVENUE,...,NaN,NaN,NaN,NaN,3522011,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
1,09/18/2016,19:09,BROOKLYN,11237.0,NaN,NaN,NaN,NaN,NaN,140 MORGAN AVENUE,...,Driver Inattention/Distraction,NaN,NaN,NaN,3522438,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
2,09/18/2016,1:09,MANHATTAN,10012.0,NaN,NaN,NaN,DELANCEY STREET,BOWERY,NaN,...,NaN,NaN,NaN,NaN,3523763,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
3,09/18/2016,1:09,NaN,NaN,40.862498,-73.934185,"(40.8624983, -73.9341848)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3524356,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
4,09/18/2016,20:09,BROOKLYN,11229.0,NaN,NaN,NaN,AVENUE W,PLUMB 1 STREET,NaN,...,NaN,NaN,NaN,NaN,3522651,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
5,09/18/2016,20:09,MANHATTAN,10003.0,NaN,NaN,NaN,NaN,NaN,355 BOWERY,...,NaN,NaN,NaN,NaN,3522315,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
6,08/25/2015,19:00,NaN,NaN,40.732941,-73.920382,"(40.7329414, -73.9203819)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3284922,PASSENGER VEHICLE,TAXI,NaN,NaN,NaN
7,07/27/2012,22:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2833714,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
8,05/17/2014,0:45,NaN,NaN,NaN,NaN,NaN,PENNSYLVANIA AVENUE,RIVERDALE AVENUE,NaN,...,NaN,NaN,NaN,NaN,336679,NaN,NaN,NaN,NaN,NaN
9,08/12/2016,1:08,QUEENS,11377.0,NaN,NaN,NaN,QUEENS BOULEVARD,69 STREET,NaN,...,NaN,NaN,NaN,NaN,3498919,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
10,08/12/2016,20:08,BRONX,10460.0,NaN,NaN,NaN,NaN,NaN,948 EAST 179 STREET,...,NaN,NaN,NaN,NaN,3499511,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
11,08/12/2016,20:08,BRONX,10466.0,NaN,NaN,NaN,EDENWALD AVENUE,BRUNER AVENUE,NaN,...,NaN,NaN,NaN,NaN,3500136,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
12,08/12/2016,20:08,BROOKLYN,11216.0,NaN,NaN,NaN,NaN,NaN,1323 FULTON STREET,...,NaN,NaN,NaN,NaN,3499591,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
13,08/12/2016,20:08,BROOKLYN,11226.0,NaN,NaN,NaN,NaN,NaN,500 OCEAN AVENUE,...,NaN,NaN,NaN,NaN,3501084,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
14,08/12/2016,20:08,BROOKLYN,11235.0,NaN,NaN,NaN,NaN,NaN,2805 AVENUE Y,...,NaN,NaN,NaN,NaN,3500227,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
15,09/18/2016,21:09,QUEENS,11420.0,NaN,NaN,NaN,NaN,NaN,114-18 120 STREET,...,NaN,NaN,NaN,NaN,3522320,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
16,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,ROGERS AVENUE,NaN,NaN,...,Other Vehicular,NaN,NaN,NaN,3523254,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN
17,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,UTOPIA PARKWAY,NaN,NaN,...,NaN,NaN,NaN,NaN,3523140,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
18,09/18/2016,22:09,BROOKLYN,11211.0,NaN,NaN,NaN,METROPOLITAN AVENUE,GARDNER AVENUE,NaN,...,NaN,NaN,NaN,NaN,3523286,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
19,08/12/2016,20:08,MANHATTAN,10036.0,NaN,NaN,NaN,10 AVENUE,WEST 41 STREET,NaN,...,NaN,NaN,NaN,NaN,3500791,SMALL COM VEH(4 TIRES),PASSENGER VEHICLE,NaN,NaN,NaN
20,08/12/2016,20:08,QUEENS,11101.0,NaN,NaN,NaN,44 DRIVE,10 STREET,NaN,...,NaN,NaN,NaN,NaN,3499705,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
21,08/12/2016,20:08,QUEENS,11377.0,NaN,NaN,NaN,NaN,NaN,69-10 34 AVENUE,...,NaN,NaN,NaN,NaN,3499764,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
22,08/12/2016,20:08,NaN,NaN,NaN,NaN,NaN,KINGS HIGHWAY,CLARENDON ROAD,NaN,...,NaN,NaN,NaN,NaN,3501024,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
23,05/03/2016,8:00,QUEENS,11385.0,40.707891,-73.909622,"(40.7078905, -73.9096224)",NaN,NaN,1934 GREENE AVENUE,...,NaN,NaN,NaN,NaN,3434031,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
24,05/03/2016,8:00,NaN,NaN,NaN,NaN,NaN,CROSSBAY BOULEVARD,SHORE PARKWAY,NaN,...,NaN,NaN,NaN,NaN,3434064,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
25,05/03/2016,8:09,BROOKLYN,11208.0,40.678828,-73.866171,"(40.6788277, -73.866171)",NaN,NaN,1168 LIBERTY AVENUE,...,NaN,NaN,NaN,NaN,3433897,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
26,05/03/2016,8:10,MANHATTAN,10031.0,40.830669,-73.944886,"(40.8306685, -73.9448864)",NaN,NaN,528 WEST 153 STREET,...,NaN,NaN,NaN,NaN,3434479,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
27,09/17/2016,13:09,STATEN ISLAND,10301.0,NaN,NaN,NaN,RICHMOND TERRACE,HAMILTON AVENUE,NaN,...,NaN,NaN,NaN,NaN,3524007,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
28,09/17/2016,13:09,NaN,NaN,NaN,NaN,NaN,MORNINGSTAR ROAD,WALKER STREET,NaN,...,NaN,NaN,NaN,NaN,3521752,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
29,09/17/2016,13:09,NaN,NaN,40.789540,-73.982252,"(40.7895396, -73.9822521)",NaN,NaN,NaN,...,Other Vehicular,Other Vehicular,Following Too Closely,NaN,3521917,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913773,07/11/2012,9:00,NaN,NaN,40.746107,-73.766791,"(40.746107, -73.7667908)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3078747,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913774,07/11/2012,9:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2912127,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913775,07/10/2012,12:00,NaN,NaN,NaN,NaN,NaN,ASTORIA BOULEVARD,31 STREET,NaN,...,NaN,NaN,NaN,NaN,272667,PASSENGER VEHICLE,PICK-UP TRUCK,NaN,NaN,NaN
913776,07/10/2012,18:00,NaN,NaN,NaN,NaN,NaN,KERMIT AVENUE,PARKINSON AVENUE,NaN,...,NaN,NaN,NaN,NaN,293261,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913777,07/10/2012,20:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2918666,PASSENGER VEHICLE,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN
913778,07/09/2012,13:45,NaN,NaN,NaN,NaN,NaN,PARK AVENUE,HALL STREET,NaN,...,NaN,NaN,NaN,NaN,191585,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913779,07/09/2012,4:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2879038,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913780,07/08/2012,22:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3016748,MOTORCYCLE,NaN,NaN,NaN,NaN
913781,07/08/2012,2:35,NaN,NaN,40.835486,-73.949394,"(40.8354859, -73.9493936)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2872826,OTHER,NaN,NaN,NaN,NaN
913782,07/07/2012,13:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3121385,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913783,07/07/2012,14:40,NaN,NaN,NaN,NaN,NaN,EAST 135 STREET,3 AVENUE,NaN,...,NaN,NaN,NaN,NaN,72655,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913784,07/07/2012,19:30,NaN,NaN,NaN,NaN,NaN,CASTLE HILL AVENUE,WESTCHESTER AVENUE,NaN,...,NaN,NaN,NaN,NaN,80874,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913785,07/07/2012,23:10,NaN,NaN,40.727873,-73.929122,"(40.727873, -73.9291223)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3044674,SPORT UTILITY / STATION WAGON,UNKNOWN,NaN,NaN,NaN
913786,07/06/2012,0:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2867735,SPORT UTILITY / STATION WAGON,TAXI,NaN,NaN,NaN
913787,07/05/2012,15:43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2864071,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913788,07/05/2012,16:30,NaN,NaN,40.767894,-73.837995,"(40.7678942, -73.8379954)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3055606,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913789,07/04/2012,9:15,NaN,NaN,NaN,NaN,NaN,BAY PARKWAY,SHORE PARKWAY,NaN,...,NaN,NaN,NaN,NaN,121421,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913790,07/03/2012,0:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896734,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913791,07/03/2012,12:35,BROOKLYN,11210.0,40.629166,-73.947326,"(40.6291662, -73.947326)",AVENUE I,NOSTRAND AVENUE,NaN,...,NaN,NaN,NaN,NaN,125685,VAN,NaN,NaN,NaN,NaN
913792,07/03/2012,16:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896732,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN,NaN
913793,07/03/2012,17:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3096749,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913794,07/03/2012,21:05,NaN,NaN,NaN,NaN,NaN,MURDOCK AVENUE,EAST 242 STREET,NaN,...,NaN,NaN,NaN,NaN,94897,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913795,07/02/2012,21:37,NaN,NaN,NaN,NaN,NaN,PELHAM PARKWAY SOUTH,HOLLAND AVENUE,NaN,...,NaN,NaN,NaN,NaN,102728,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913796,07/01/2012,21:55,QUEENS,11368.0,40.753565,-73.870695,"(40.7535645, -73.8706949)",97 STREET,35 AVENUE,NaN,...,NaN,NaN,NaN,NaN,279645,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913797,07/01/2012,4:44,MANHATTAN,10001.0,40.746659,-73.990068,"(40.7466595, -73.9900681)",6 AVENUE,WEST 29 STREET,NaN,...,NaN,NaN,NaN,NaN,26084,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913798,07/01/2012,7:00,NaN,NaN,NaN,NaN,NaN,BEACH 54 STREET,ROCKAWAY BEACH BOULEVARD,NaN,...,NaN,NaN,NaN,NaN,202242,PASSENGER VEHICLE,VAN,NaN,NaN,NaN
913799,07/01/2012,9:15,BROOKLYN,11233.0,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,NaN,...,NaN,NaN,NaN,NaN,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913800,07/01/2012,9:15,QUEENS,11421.0,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,NaN,...,NaN,NaN,NaN,NaN,203690,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913801,07/01/2012,9:15,QUEENS,11429.0,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,NaN,...,NaN,NaN,NaN,NaN,219394,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913802,07/01/2012,9:15,STATEN ISLAND,10310.0,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,NaN,...,NaN,NaN,NaN,NaN,284646,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN

In [12]:
# df_1[['ZIP CODE']] = df_1[['ZIP CODE']].fillna(int(0)).astype(int)

In [13]:
df_1.index = np.arange(1, len(df_1) + 1)

In [14]:
df_1

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
1,09/18/2016,19:09,QUEENS,11422.0,NaN,NaN,NaN,NaN,NaN,234-32 131 AVENUE,...,NaN,NaN,NaN,NaN,3522011,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
2,09/18/2016,19:09,BROOKLYN,11237.0,NaN,NaN,NaN,NaN,NaN,140 MORGAN AVENUE,...,Driver Inattention/Distraction,NaN,NaN,NaN,3522438,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
3,09/18/2016,1:09,MANHATTAN,10012.0,NaN,NaN,NaN,DELANCEY STREET,BOWERY,NaN,...,NaN,NaN,NaN,NaN,3523763,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
4,09/18/2016,1:09,NaN,NaN,40.862498,-73.934185,"(40.8624983, -73.9341848)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3524356,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
5,09/18/2016,20:09,BROOKLYN,11229.0,NaN,NaN,NaN,AVENUE W,PLUMB 1 STREET,NaN,...,NaN,NaN,NaN,NaN,3522651,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
6,09/18/2016,20:09,MANHATTAN,10003.0,NaN,NaN,NaN,NaN,NaN,355 BOWERY,...,NaN,NaN,NaN,NaN,3522315,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
7,08/25/2015,19:00,NaN,NaN,40.732941,-73.920382,"(40.7329414, -73.9203819)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3284922,PASSENGER VEHICLE,TAXI,NaN,NaN,NaN
8,07/27/2012,22:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2833714,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
9,05/17/2014,0:45,NaN,NaN,NaN,NaN,NaN,PENNSYLVANIA AVENUE,RIVERDALE AVENUE,NaN,...,NaN,NaN,NaN,NaN,336679,NaN,NaN,NaN,NaN,NaN
10,08/12/2016,1:08,QUEENS,11377.0,NaN,NaN,NaN,QUEENS BOULEVARD,69 STREET,NaN,...,NaN,NaN,NaN,NaN,3498919,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
11,08/12/2016,20:08,BRONX,10460.0,NaN,NaN,NaN,NaN,NaN,948 EAST 179 STREET,...,NaN,NaN,NaN,NaN,3499511,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
12,08/12/2016,20:08,BRONX,10466.0,NaN,NaN,NaN,EDENWALD AVENUE,BRUNER AVENUE,NaN,...,NaN,NaN,NaN,NaN,3500136,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
13,08/12/2016,20:08,BROOKLYN,11216.0,NaN,NaN,NaN,NaN,NaN,1323 FULTON STREET,...,NaN,NaN,NaN,NaN,3499591,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
14,08/12/2016,20:08,BROOKLYN,11226.0,NaN,NaN,NaN,NaN,NaN,500 OCEAN AVENUE,...,NaN,NaN,NaN,NaN,3501084,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
15,08/12/2016,20:08,BROOKLYN,11235.0,NaN,NaN,NaN,NaN,NaN,2805 AVENUE Y,...,NaN,NaN,NaN,NaN,3500227,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
16,09/18/2016,21:09,QUEENS,11420.0,NaN,NaN,NaN,NaN,NaN,114-18 120 STREET,...,NaN,NaN,NaN,NaN,3522320,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
17,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,ROGERS AVENUE,NaN,NaN,...,Other Vehicular,NaN,NaN,NaN,3523254,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN
18,09/18/2016,21:09,NaN,NaN,NaN,NaN,NaN,UTOPIA PARKWAY,NaN,NaN,...,NaN,NaN,NaN,NaN,3523140,PICK-UP TRUCK,PASSENGER VEHICLE,NaN,NaN,NaN
19,09/18/2016,22:09,BROOKLYN,11211.0,NaN,NaN,NaN,METROPOLITAN AVENUE,GARDNER AVENUE,NaN,...,NaN,NaN,NaN,NaN,3523286,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
20,08/12/2016,20:08,MANHATTAN,10036.0,NaN,NaN,NaN,10 AVENUE,WEST 41 STREET,NaN,...,NaN,NaN,NaN,NaN,3500791,SMALL COM VEH(4 TIRES),PASSENGER VEHICLE,NaN,NaN,NaN
21,08/12/2016,20:08,QUEENS,11101.0,NaN,NaN,NaN,44 DRIVE,10 STREET,NaN,...,NaN,NaN,NaN,NaN,3499705,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
22,08/12/2016,20:08,QUEENS,11377.0,NaN,NaN,NaN,NaN,NaN,69-10 34 AVENUE,...,NaN,NaN,NaN,NaN,3499764,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
23,08/12/2016,20:08,NaN,NaN,NaN,NaN,NaN,KINGS HIGHWAY,CLARENDON ROAD,NaN,...,NaN,NaN,NaN,NaN,3501024,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
24,05/03/2016,8:00,QUEENS,11385.0,40.707891,-73.909622,"(40.7078905, -73.9096224)",NaN,NaN,1934 GREENE AVENUE,...,NaN,NaN,NaN,NaN,3434031,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
25,05/03/2016,8:00,NaN,NaN,NaN,NaN,NaN,CROSSBAY BOULEVARD,SHORE PARKWAY,NaN,...,NaN,NaN,NaN,NaN,3434064,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
26,05/03/2016,8:09,BROOKLYN,11208.0,40.678828,-73.866171,"(40.6788277, -73.866171)",NaN,NaN,1168 LIBERTY AVENUE,...,NaN,NaN,NaN,NaN,3433897,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
27,05/03/2016,8:10,MANHATTAN,10031.0,40.830669,-73.944886,"(40.8306685, -73.9448864)",NaN,NaN,528 WEST 153 STREET,...,NaN,NaN,NaN,NaN,3434479,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
28,09/17/2016,13:09,STATEN ISLAND,10301.0,NaN,NaN,NaN,RICHMOND TERRACE,HAMILTON AVENUE,NaN,...,NaN,NaN,NaN,NaN,3524007,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
29,09/17/2016,13:09,NaN,NaN,NaN,NaN,NaN,MORNINGSTAR ROAD,WALKER STREET,NaN,...,NaN,NaN,NaN,NaN,3521752,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
30,09/17/2016,13:09,NaN,NaN,40.789540,-73.982252,"(40.7895396, -73.9822521)",NaN,NaN,NaN,...,Other Vehicular,Other Vehicular,Following Too Closely,NaN,3521917,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913774,07/11/2012,9:00,NaN,NaN,40.746107,-73.766791,"(40.746107, -73.7667908)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3078747,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913775,07/11/2012,9:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2912127,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913776,07/10/2012,12:00,NaN,NaN,NaN,NaN,NaN,ASTORIA BOULEVARD,31 STREET,NaN,...,NaN,NaN,NaN,NaN,272667,PASSENGER VEHICLE,PICK-UP TRUCK,NaN,NaN,NaN
913777,07/10/2012,18:00,NaN,NaN,NaN,NaN,NaN,KERMIT AVENUE,PARKINSON AVENUE,NaN,...,NaN,NaN,NaN,NaN,293261,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913778,07/10/2012,20:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2918666,PASSENGER VEHICLE,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN
913779,07/09/2012,13:45,NaN,NaN,NaN,NaN,NaN,PARK AVENUE,HALL STREET,NaN,...,NaN,NaN,NaN,NaN,191585,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913780,07/09/2012,4:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2879038,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913781,07/08/2012,22:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3016748,MOTORCYCLE,NaN,NaN,NaN,NaN
913782,07/08/2012,2:35,NaN,NaN,40.835486,-73.949394,"(40.8354859, -73.9493936)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2872826,OTHER,NaN,NaN,NaN,NaN
913783,07/07/2012,13:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3121385,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913784,07/07/2012,14:40,NaN,NaN,NaN,NaN,NaN,EAST 135 STREET,3 AVENUE,NaN,...,NaN,NaN,NaN,NaN,72655,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913785,07/07/2012,19:30,NaN,NaN,NaN,NaN,NaN,CASTLE HILL AVENUE,WESTCHESTER AVENUE,NaN,...,NaN,NaN,NaN,NaN,80874,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913786,07/07/2012,23:10,NaN,NaN,40.727873,-73.929122,"(40.727873, -73.9291223)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3044674,SPORT UTILITY / STATION WAGON,UNKNOWN,NaN,NaN,NaN
913787,07/06/2012,0:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2867735,SPORT UTILITY / STATION WAGON,TAXI,NaN,NaN,NaN
913788,07/05/2012,15:43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2864071,OTHER,PASSENGER VEHICLE,NaN,NaN,NaN
913789,07/05/2012,16:30,NaN,NaN,40.767894,-73.837995,"(40.7678942, -73.8379954)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3055606,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913790,07/04/2012,9:15,NaN,NaN,NaN,NaN,NaN,BAY PARKWAY,SHORE PARKWAY,NaN,...,NaN,NaN,NaN,NaN,121421,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913791,07/03/2012,0:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896734,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913792,07/03/2012,12:35,BROOKLYN,11210.0,40.629166,-73.947326,"(40.6291662, -73.947326)",AVENUE I,NOSTRAND AVENUE,NaN,...,NaN,NaN,NaN,NaN,125685,VAN,NaN,NaN,NaN,NaN
913793,07/03/2012,16:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2896732,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN,NaN
913794,07/03/2012,17:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3096749,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913795,07/03/2012,21:05,NaN,NaN,NaN,NaN,NaN,MURDOCK AVENUE,EAST 242 STREET,NaN,...,NaN,NaN,NaN,NaN,94897,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913796,07/02/2012,21:37,NaN,NaN,NaN,NaN,NaN,PELHAM PARKWAY SOUTH,HOLLAND AVENUE,NaN,...,NaN,NaN,NaN,NaN,102728,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913797,07/01/2012,21:55,QUEENS,11368.0,40.753565,-73.870695,"(40.7535645, -73.8706949)",97 STREET,35 AVENUE,NaN,...,NaN,NaN,NaN,NaN,279645,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
913798,07/01/2012,4:44,MANHATTAN,10001.0,40.746659,-73.990068,"(40.7466595, -73.9900681)",6 AVENUE,WEST 29 STREET,NaN,...,NaN,NaN,NaN,NaN,26084,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
913799,07/01/2012,7:00,NaN,NaN,NaN,NaN,NaN,BEACH 54 STREET,ROCKAWAY BEACH BOULEVARD,NaN,...,NaN,NaN,NaN,NaN,202242,PASSENGER VEHICLE,VAN,NaN,NaN,NaN
913800,07/01/2012,9:15,BROOKLYN,11233.0,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,NaN,...,NaN,NaN,NaN,NaN,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
913801,07/01/2012,9:15,QUEENS,11421.0,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,NaN,...,NaN,NaN,NaN,NaN,203690,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
913802,07/01/2012,9:15,QUEENS,11429.0,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,NaN,...,NaN,NaN,NaN,NaN,219394,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
913803,07/01/2012,9:15,STATEN ISLAND,10310.0,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,NaN,...,NaN,NaN,NaN,NaN,284646,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN

In [15]:
#df.ix[1]

In [16]:
#df_1.ix[[1]]

In [17]:
#df_1.loc[[1]]

In [18]:
#df_1.loc[1]

In [19]:
#df_1.iloc[[1]]

In [20]:
#df_1.iloc[1]

In [21]:
#df_1.sort_values(['BOROUGH', 'ZIP CODE'])

In [22]:
#gp_1 = df_1.groupby(['ZIP CODE'])

In [23]:
#gp_zipcode = gp_1['ZIP CODE']

In [24]:
#zipcode_count = gp_zipcode.agg(['count'])

In [25]:
#type(zipcode_count)

In [26]:
zipcode_count = df_1.groupby(['ZIP CODE'])['ZIP CODE'].count()

In [35]:
zipcode_count = zipcode_count.sort_values()

In [27]:
type(zipcode_count)

pandas.core.series.Series

In [36]:
zipcode_count

ZIP CODE
11251.0        1
11242.0        1
10103.0        1
10153.0        3
10123.0        3
10803.0        4
11359.0        9
11695.0       10
10111.0       18
10281.0       38
10048.0       50
10000.0       51
11005.0       54
10282.0       62
11109.0       79
11430.0       81
11697.0       83
10280.0      140
10119.0      145
10069.0      158
11040.0      210
11001.0      275
10464.0      414
10020.0      440
10302.0      520
10303.0      551
10307.0      632
10005.0      741
11360.0      744
11692.0      811
           ...
11377.0     6033
10011.0     6057
11211.0     6073
10017.0     6177
11354.0     6299
11233.0     6472
11230.0     6482
10467.0     6543
11206.0     6560
11213.0     6599
11212.0     6633
10018.0     6636
11220.0     6929
11208.0     6993
11434.0     7174
11226.0     7300
10002.0     7434
11234.0     7446
11385.0     7576
11236.0     7666
10013.0     7931
11203.0     8212
10001.0     8729
11201.0     8944
10036.0     9112
10019.0     9482
10022.0     9624
10016.0     9794
11101.0     9899
11207.0    12138
Name: ZIP CODE, dtype: int64

In [29]:
import matplotlib.pyplot as plt

In [53]:
y = zipcode_count.values
x = zipcode_count.index
width = 24
pic_1 = plt.bar(x, y, width, color="orange")
plt.show()

In [43]:
borough_count = df_1.groupby(['BOROUGH'])['BOROUGH'].count()

In [44]:
borough_count

BOROUGH
BRONX             88230
BROOKLYN         208521
MANHATTAN        176856
QUEENS           176260
STATEN ISLAND     31692
Name: BOROUGH, dtype: int64

In [50]:
y = borough_count.values
x = range(5)
labels = borough_count.index
width = 0.8
pic_2 = plt.bar(x, y, width, color="orange")
plt.xticks(x, labels)
plt.show()

In [24]:
type(borough_count)

pandas.core.series.Series

In [25]:
borough_df = borough_count.to_frame("BoroughCount").reset_index()

In [26]:
borough_df

         BOROUGH  BoroughCount
0          BRONX         88230
1       BROOKLYN        208521
2      MANHATTAN        176856
3         QUEENS        176260
4  STATEN ISLAND         31692

In [28]:
zipcode_df = zipcode_count.to_frame("ZipCount").reset_index()

In [30]:
zipcode_df

     ZIP CODE  ZipCount
0     10000.0        51
1     10001.0      8729
2     10002.0      7434
3     10003.0      5747
4     10004.0      1277
5     10005.0       741
6     10006.0       870
7     10007.0      2236
8     10009.0      3306
9     10010.0      4477
10    10011.0      6057
11    10012.0      4466
12    10013.0      7931
13    10014.0      3772
14    10016.0      9794
15    10017.0      6177
16    10018.0      6636
17    10019.0      9482
18    10020.0       440
19    10021.0      3696
20    10022.0      9624
21    10023.0      4313
22    10024.0      3786
23    10025.0      4395
24    10026.0      1923
25    10027.0      4913
26    10028.0      2681
27    10029.0      5630
28    10030.0      1973
29    10031.0      2823
..        ...       ...
165   11385.0      7576
166   11411.0      1845
167   11412.0      2960
168   11413.0      4417
169   11414.0      1856
170   11415.0      1273
171   11416.0      2114
172   11417.0      3225
173   11418.0      3026
174   11419.0      3904
175   11420.0      4208
176   11421.0      2561
177   11422.0      3979
178   11423.0      2491
179   11426.0      1293
180   11427.0      1751
181   11428.0      1628
182   11429.0      2021
183   11430.0        81
184   11432.0      5023
185   11433.0      3213
186   11434.0      7174
187   11435.0      4132
188   11436.0      1444
189   11691.0      3117
190   11692.0       811
191   11693.0       839
192   11694.0       931
193   11695.0        10
194   11697.0        83

[195 rows x 2 columns]

In [31]:
area = df_1[['BOROUGH', 'ZIP CODE']]

In [32]:
area = area.dropna(how='all')

In [33]:
area

              BOROUGH  ZIP CODE
1              QUEENS   11422.0
2            BROOKLYN   11237.0
3           MANHATTAN   10012.0
5            BROOKLYN   11229.0
6           MANHATTAN   10003.0
10             QUEENS   11377.0
11              BRONX   10460.0
12              BRONX   10466.0
13           BROOKLYN   11216.0
14           BROOKLYN   11226.0
15           BROOKLYN   11235.0
16             QUEENS   11420.0
19           BROOKLYN   11211.0
20          MANHATTAN   10036.0
21             QUEENS   11101.0
22             QUEENS   11377.0
24             QUEENS   11385.0
26           BROOKLYN   11208.0
27          MANHATTAN   10031.0
28      STATEN ISLAND   10301.0
31             QUEENS   11432.0
34          MANHATTAN   10075.0
35              BRONX   10461.0
36              BRONX   10465.0
37           BROOKLYN   11223.0
38          MANHATTAN   10018.0
39      STATEN ISLAND   10312.0
42           BROOKLYN   11234.0
43           BROOKLYN   11235.0
44          MANHATTAN   10024.0
...               ...       ...
913593         QUEENS   11354.0
913595          BRONX   10456.0
913617      MANHATTAN   10024.0
913618      MANHATTAN   10029.0
913619      MANHATTAN   10037.0
913620         QUEENS   11691.0
913626      MANHATTAN   10036.0
913627      MANHATTAN   10010.0
913628       BROOKLYN   11218.0
913629       BROOKLYN   11219.0
913662          BRONX   10451.0
913663      MANHATTAN   10027.0
913664          BRONX   10469.0
913679         QUEENS   11416.0
913687      MANHATTAN   10001.0
913689          BRONX   10462.0
913690  STATEN ISLAND   10306.0
913728          BRONX   10463.0
913729      MANHATTAN   10013.0
913730       BROOKLYN   11233.0
913739         QUEENS   11355.0
913745          BRONX   10466.0
913746         QUEENS   11373.0
913792       BROOKLYN   11210.0
913797         QUEENS   11368.0
913798      MANHATTAN   10001.0
913800       BROOKLYN   11233.0
913801         QUEENS   11421.0
913802         QUEENS   11429.0
913803  STATEN ISLAND   10310.0

[681559 rows x 2 columns]

In [34]:
area = area.merge(borough_df, how='left',left_on='BOROUGH', right_on='BOROUGH')

In [35]:
area = area.merge(zipcode_df, how='left',left_on='ZIP CODE', right_on='ZIP CODE')

In [36]:
area

              BOROUGH  ZIP CODE  BoroughCount  ZipCount
0              QUEENS   11422.0        176260    3979.0
1            BROOKLYN   11237.0        208521    3730.0
2           MANHATTAN   10012.0        176856    4466.0
3            BROOKLYN   11229.0        208521    5009.0
4           MANHATTAN   10003.0        176856    5747.0
5              QUEENS   11377.0        176260    6033.0
6               BRONX   10460.0         88230    4193.0
7               BRONX   10466.0         88230    5133.0
8            BROOKLYN   11216.0        208521    5868.0
9            BROOKLYN   11226.0        208521    7300.0
10           BROOKLYN   11235.0        208521    5766.0
11             QUEENS   11420.0        176260    4208.0
12           BROOKLYN   11211.0        208521    6073.0
13          MANHATTAN   10036.0        176856    9112.0
14             QUEENS   11101.0        176260    9899.0
15             QUEENS   11377.0        176260    6033.0
16             QUEENS   11385.0        176260    7576.0
17           BROOKLYN   11208.0        208521    6993.0
18          MANHATTAN   10031.0        176856    2823.0
19      STATEN ISLAND   10301.0         31692    3767.0
20             QUEENS   11432.0        176260    5023.0
21          MANHATTAN   10075.0        176856    2001.0
22              BRONX   10461.0         88230    4349.0
23              BRONX   10465.0         88230    2484.0
24           BROOKLYN   11223.0        208521    5507.0
25          MANHATTAN   10018.0        176856    6636.0
26      STATEN ISLAND   10312.0         31692    4034.0
27           BROOKLYN   11234.0        208521    7446.0
28           BROOKLYN   11235.0        208521    5766.0
29          MANHATTAN   10024.0        176856    3786.0
...               ...       ...           ...       ...
681529         QUEENS   11354.0        176260    6299.0
681530          BRONX   10456.0         88230    3797.0
681531      MANHATTAN   10024.0        176856    3786.0
681532      MANHATTAN   10029.0        176856    5630.0
681533      MANHATTAN   10037.0        176856    1811.0
681534         QUEENS   11691.0        176260    3117.0
681535      MANHATTAN   10036.0        176856    9112.0
681536      MANHATTAN   10010.0        176856    4477.0
681537       BROOKLYN   11218.0        208521    4849.0
681538       BROOKLYN   11219.0        208521    5121.0
681539          BRONX   10451.0         88230    4567.0
681540      MANHATTAN   10027.0        176856    4913.0
681541          BRONX   10469.0         88230    4524.0
681542         QUEENS   11416.0        176260    2114.0
681543      MANHATTAN   10001.0        176856    8729.0
681544          BRONX   10462.0         88230    3914.0
681545  STATEN ISLAND   10306.0         31692    5219.0
681546          BRONX   10463.0         88230    3544.0
681547      MANHATTAN   10013.0        176856    7931.0
681548       BROOKLYN   11233.0        208521    6472.0
681549         QUEENS   11355.0        176260    5819.0
681550          BRONX   10466.0         88230    5133.0
681551         QUEENS   11373.0        176260    5664.0
681552       BROOKLYN   11210.0        208521    5114.0
681553         QUEENS   11368.0        176260    5274.0
681554      MANHATTAN   10001.0        176856    8729.0
681555       BROOKLYN   11233.0        208521    6472.0
681556         QUEENS   11421.0        176260    2561.0
681557         QUEENS   11429.0        176260    2021.0
681558  STATEN ISLAND   10310.0         31692    2197.0

[681559 rows x 4 columns]

In [38]:
area = area.sort_values(['BOROUGH', 'ZIP CODE']).reset_index()

In [39]:
area

         index        BOROUGH  ZIP CODE  BoroughCount  ZipCount
0          583          BRONX   10451.0         88230    4567.0
1         1004          BRONX   10451.0         88230    4567.0
2         1197          BRONX   10451.0         88230    4567.0
3         1255          BRONX   10451.0         88230    4567.0
4         1383          BRONX   10451.0         88230    4567.0
5         1503          BRONX   10451.0         88230    4567.0
6         1525          BRONX   10451.0         88230    4567.0
7         1632          BRONX   10451.0         88230    4567.0
8         1720          BRONX   10451.0         88230    4567.0
9         1742          BRONX   10451.0         88230    4567.0
10        1744          BRONX   10451.0         88230    4567.0
11        1835          BRONX   10451.0         88230    4567.0
12        1878          BRONX   10451.0         88230    4567.0
13        1908          BRONX   10451.0         88230    4567.0
14        2008          BRONX   10451.0         88230    4567.0
15        2113          BRONX   10451.0         88230    4567.0
16        2229          BRONX   10451.0         88230    4567.0
17        2359          BRONX   10451.0         88230    4567.0
18        2486          BRONX   10451.0         88230    4567.0
19        2609          BRONX   10451.0         88230    4567.0
20        2669          BRONX   10451.0         88230    4567.0
21        2676          BRONX   10451.0         88230    4567.0
22        2731          BRONX   10451.0         88230    4567.0
23        3113          BRONX   10451.0         88230    4567.0
24        3215          BRONX   10451.0         88230    4567.0
25        3309          BRONX   10451.0         88230    4567.0
26        3410          BRONX   10451.0         88230    4567.0
27        3714          BRONX   10451.0         88230    4567.0
28        4262          BRONX   10451.0         88230    4567.0
29        4393          BRONX   10451.0         88230    4567.0
...        ...            ...       ...           ...       ...
681529  674629  STATEN ISLAND   10314.0         31692    3207.0
681530  674725  STATEN ISLAND   10314.0         31692    3207.0
681531  674971  STATEN ISLAND   10314.0         31692    3207.0
681532  675480  STATEN ISLAND   10314.0         31692    3207.0
681533  675517  STATEN ISLAND   10314.0         31692    3207.0
681534  675996  STATEN ISLAND   10314.0         31692    3207.0
681535  676031  STATEN ISLAND   10314.0         31692    3207.0
681536  677008  STATEN ISLAND   10314.0         31692    3207.0
681537  677493  STATEN ISLAND   10314.0         31692    3207.0
681538  677843  STATEN ISLAND   10314.0         31692    3207.0
681539  677988  STATEN ISLAND   10314.0         31692    3207.0
681540  679587  STATEN ISLAND   10314.0         31692    3207.0
681541  679644  STATEN ISLAND   10314.0         31692    3207.0
681542  679658  STATEN ISLAND   10314.0         31692    3207.0
681543  679712  STATEN ISLAND   10314.0         31692    3207.0
681544  679774  STATEN ISLAND   10314.0         31692    3207.0
681545  679956  STATEN ISLAND   10314.0         31692    3207.0
681546  680084  STATEN ISLAND   10314.0         31692    3207.0
681547  680099  STATEN ISLAND   10314.0         31692    3207.0
681548  680220  STATEN ISLAND   10314.0         31692    3207.0
681549  680298  STATEN ISLAND   10314.0         31692    3207.0
681550  680381  STATEN ISLAND   10314.0         31692    3207.0
681551  680556  STATEN ISLAND   10314.0         31692    3207.0
681552  680692  STATEN ISLAND   10314.0         31692    3207.0
681553  680933  STATEN ISLAND   10314.0         31692    3207.0
681554  680950  STATEN ISLAND   10314.0         31692    3207.0
681555  680993  STATEN ISLAND   10314.0         31692    3207.0
681556  681226  STATEN ISLAND   10314.0         31692    3207.0
681557  681287  STATEN ISLAND   10314.0         31692    3207.0
681558  681514  STATEN ISLAND   10314.0         31692    3207.0

[681559 rows x 5 columns]